### ISSUE TITLE
Search does not work for ONEOPS docs

### ISSUE THREAD

**Issue by ravivangara17** [oneops/oneops.github.io#4]
Search does not work at the following URL

https://oneops.github.io/documentation/user.html

**Comment by mosabua** [comment]
I am working on search now. We will deploy a new build either without search or with a fixed search asap.

**Comment by jitendrakrgupta** [comment]
@mosabua - Any idea by when can this be fixed ?

**Comment by mosabua** [comment]
@jitendrakrgupta we are going to publish an update to the site later today that fixes incoming as well as internal link problems. The site will then be consistent and working. The next step will be to refresh the search index and that should do the trick. So very soon..

**Comment by mosabua** [comment]
Launched new site and added searchmap.json. Search seems operational now. However there are still issues with the index it seems so some results go to 404 pages. 

E.g. http://oneops.com/user/howto/enable-https-for-a-service-lb-certs.html.html

**Comment by mosabua** [comment]
Also note that the oneops.github.io URL redirects to oneops.com per DNS entry now. Use the site off that main domain to see if there are further issues.

**Comment by mosabua** [comment]
E.g. URLs are 

http://oneops.com/user/overview/
http://oneops.com/developer/getting-started/

**Comment by mosabua** [comment]
The site is now live with 0 internal link errors. The only problem is that the search index is still stale and has wrong links. I re-added the required searchmap.json file and worked with @gauravlall and @mtunganati on the admin side of things. Turns out that the produced searchmap.json is currently invalid .. so I am now investigating the the liquid script that produces the JSON and the output to find the offending script or content. fyi @aliloney

**Comment by mosabua** [comment]
I found that a lot of the source code md files have tabs in them, which invalidate the json when the content is inserted there. All tabs are now removed and the site is republished. The JSON files are now valid .. but I still get error messages when trying to force an index update via CURL on the search server.

**Comment by mosabua** [comment]
Added redirectors e.g. from /user to user.html to avoid another dead link problem.

**Comment by mosabua** [comment]
With the updated JSON it seems like the search results somehow updated itself even though the manual curl based index kick failed again. So at this stage from all I can tell the search works and does not link to any wrong pages anymore at all. At least I could not find any. If anyone following this item can find problems please let me know. 

I will still work on figuring out the search more but the urgent issue about it not working seems to be completely resolved now.  fyi also @kfilipovski @jvanzyl

**Comment by mosabua** [comment]
I am closing this for now .. if anything breaks or seems off please file a new issue and I investigate. For now it seems to be working as expected.

**Comment by jksgit** [comment]
Hi,

I am still experiencing search issues. 

Trying to search with keyword "Load" and browsing http://oneops.com/admin/howto/load-content.html, Please refer the screenshots attached.

<img width="1095" alt="screen shot 2016-12-05 at 11 34 39 am" src="https://cloud.githubusercontent.com/assets/19423396/20875237/18b464ba-badf-11e6-949b-ccde7e28698d.png">
<img width="1071" alt="screen shot 2016-12-05 at 11 31 59 am" src="https://cloud.githubusercontent.com/assets/19423396/20875238/18b66d1e-badf-11e6-85f5-ffc66214de0c.png">

**Comment by jksgit** [comment]
>Please reopen the issue.
